/*
 * Copyright (c) 2020 Linumiz
 * Author: Parthiban Nallathambi <parthiban@linumiz.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_XMC_CCU_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_XMC_CCU_H_

#define XMC_SCU_PRSTAT1_MSK			0x10000000UL
#define XMC_SCU_PRSTAT2_MSK			0x20000000UL
#define XMC_SCU_PRSTAT3_MSK			0x30000000UL
#define XMC_SCU_CGATSTAT1_MSK			0x10000000UL
#define XMC_SCU_CGATSTAT2_MSK			0x20000000UL
#define XMC_SCU_CGATSTAT3_MSK			0x30000000UL

/* peripheral reset */
#define XMC_SCU_PERIPHERAL_RESET_VADC		(0x1UL)
#define XMC_SCU_PERIPHERAL_RESET_DSD		(0x2UL)
#define XMC_SCU_PERIPHERAL_RESET_CCU40		(0x4UL)
#define XMC_SCU_PERIPHERAL_RESET_CCU41		(0x8UL)
#define XMC_SCU_PERIPHERAL_RESET_CCU42		(0x10UL)
#define XMC_SCU_PERIPHERAL_RESET_CCU80		(0x80UL)
#define XMC_SCU_PERIPHERAL_RESET_CCU81		(0x100UL)
#define XMC_SCU_PERIPHERAL_RESET_POSIF0		(0x200UL)
#define XMC_SCU_PERIPHERAL_RESET_POSIF1		(0x400UL)
#define XMC_SCU_PERIPHERAL_RESET_USIC0		(0x800UL)
#define XMC_SCU_PERIPHERAL_RESET_ERU1		(0x10000UL)
#define XMC_SCU_PERIPHERAL_RESET_HRPWM0		(0x800000UL)
#define XMC_SCU_PERIPHERAL_RESET_CCU43		(XMC_SCU_PRSTAT1_MSK | 0x1UL)
#define XMC_SCU_PERIPHERAL_RESET_LEDTS0		(XMC_SCU_PRSTAT1_MSK | 0x8UL)
#define XMC_SCU_PERIPHERAL_RESET_MCAN		(XMC_SCU_PRSTAT1_MSK | 0x10UL)
#define XMC_SCU_PERIPHERAL_RESET_DAC		(XMC_SCU_PRSTAT1_MSK | 0x20UL)
#define XMC_SCU_PERIPHERAL_RESET_SDMMC		(XMC_SCU_PRSTAT1_MSK | 0x40UL)
#define XMC_SCU_PERIPHERAL_RESET_USIC1		(XMC_SCU_PRSTAT1_MSK | 0x80UL)
#define XMC_SCU_PERIPHERAL_RESET_USIC2		(XMC_SCU_PRSTAT1_MSK | 0x100UL)
#define XMC_SCU_PERIPHERAL_RESET_PORTS		(XMC_SCU_PRSTAT1_MSK | 0x200UL)
#define XMC_SCU_PERIPHERAL_RESET_WDT		(XMC_SCU_PRSTAT2_MSK | 0x2UL)
#define XMC_SCU_PERIPHERAL_RESET_ETH0		(XMC_SCU_PRSTAT2_MSK | 0x4UL)
#define XMC_SCU_PERIPHERAL_RESET_GPDMA0		(XMC_SCU_PRSTAT2_MSK | 0x10UL)
#define XMC_SCU_PERIPHERAL_RESET_GPDMA1		(XMC_SCU_PRSTAT2_MSK | 0x20UL)
#define XMC_SCU_PERIPHERAL_RESET_FCE		(XMC_SCU_PRSTAT2_MSK | 0x40UL)
#define XMC_SCU_PERIPHERAL_RESET_USB0		(XMC_SCU_PRSTAT2_MSK | 0x80UL)
#define XMC_SCU_PERIPHERAL_RESET_ECAT0		(XMC_SCU_PRSTAT2_MSK | 0x400UL)
#define XMC_SCU_PERIPHERAL_RESET_EBU		(XMC_SCU_PRSTAT3_MSK | 0x4UL)

/* peripheral clock */
#define XMC_SCU_PERIPHERAL_CLOCK_VADC		(0x1UL)
#define XMC_SCU_PERIPHERAL_CLOCK_DSD		(0x2UL)
#define XMC_SCU_PERIPHERAL_CLOCK_CCU40		(0x4UL)
#define XMC_SCU_PERIPHERAL_CLOCK_CCU41		(0x8UL)
#define XMC_SCU_PERIPHERAL_CLOCK_CCU42		(0x10UL)
#define XMC_SCU_PERIPHERAL_CLOCK_CCU80		(0x80UL)
#define XMC_SCU_PERIPHERAL_CLOCK_CCU81		(0x100UL)
#define XMC_SCU_PERIPHERAL_CLOCK_POSIF0		(0x200UL)
#define XMC_SCU_PERIPHERAL_CLOCK_POSIF1		(0x400UL)
#define XMC_SCU_PERIPHERAL_CLOCK_USIC0		(0x800UL)
#define XMC_SCU_PERIPHERAL_CLOCK_ERU1		(0x10000UL)
#define XMC_SCU_PERIPHERAL_CLOCK_HRPWM0		(0x800000UL)
#define XMC_SCU_PERIPHERAL_CLOCK_CCU43		(XMC_SCU_CGATSTAT1_MSK | 0x1UL)
#define XMC_SCU_PERIPHERAL_CLOCK_LEDTS0		(XMC_SCU_CGATSTAT1_MSK | 0x8UL)
#define XMC_SCU_PERIPHERAL_CLOCK_MCAN		(XMC_SCU_CGATSTAT1_MSK | 0x10UL)
#define XMC_SCU_PERIPHERAL_CLOCK_DAC		(XMC_SCU_CGATSTAT1_MSK | 0x20UL)
#define XMC_SCU_PERIPHERAL_CLOCK_SDMMC		(XMC_SCU_CGATSTAT1_MSK | 0x40UL)
#define XMC_SCU_PERIPHERAL_CLOCK_USIC1		(XMC_SCU_CGATSTAT1_MSK | 0x80UL)
#define XMC_SCU_PERIPHERAL_CLOCK_USIC2		(XMC_SCU_CGATSTAT1_MSK | 0x100UL)
#define XMC_SCU_PERIPHERAL_CLOCK_PORTS		(XMC_SCU_CGATSTAT1_MSK | 0x200UL)
#define XMC_SCU_PERIPHERAL_CLOCK_WDT		(XMC_SCU_CGATSTAT2_MSK | 0x2UL)
#define XMC_SCU_PERIPHERAL_CLOCK_ETH0		(XMC_SCU_CGATSTAT2_MSK | 0x4UL)
#define XMC_SCU_PERIPHERAL_CLOCK_GPDMA0		(XMC_SCU_CGATSTAT2_MSK | 0x10UL)
#define XMC_SCU_PERIPHERAL_CLOCK_GPDMA1		(XMC_SCU_CGATSTAT2_MSK | 0x20UL)
#define XMC_SCU_PERIPHERAL_CLOCK_FCE		(XMC_SCU_CGATSTAT2_MSK | 0x40UL)
#define XMC_SCU_PERIPHERAL_CLOCK_USB0		(XMC_SCU_CGATSTAT2_MSK | 0x80UL)
#define XMC_SCU_PERIPHERAL_CLOCK_ECAT0		(XMC_SCU_CGATSTAT2_MSK | 0x400UL)
#define XMC_SCU_PERIPHERAL_CLOCK_EBU		(XMC_SCU_CGATSTAT3_MSK | 0x4UL)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_XMC_CCU_H_ */
